Generate Random Number

In [2]:
#Generate a random integer from 0 to 100
from numpy import random
x = random.randint(100)
print(x)

92


Generate Random Float

*The random module's rand() method returns a random float between 0 and 1.

In [4]:
#Generate a random float from 0 to 1
from numpy import random
x = random.rand()
print(x)

0.887879448494815


Generate Random Array

In [8]:
#Generate a 1-D array containing 5 random integers from 0 to 100
from numpy import random
x = random.randint(100, size=(7))
print(x)

[95  8 35 98 26 27 22]


In [9]:
#Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100
from numpy import random
x = random.randint(100, size=(3, 5))
print(x)

[[80 44 34  6 49]
 [51 36 19 41 74]
 [65 93 57 24 21]]


Floats

*The rand() method also allows you to specify the shape of the array

In [10]:
#Generate a 1-D array containing 5 random floats
from numpy import random
x = random.rand(5)
print(x)

[0.09311183 0.05946631 0.4947171  0.78496634 0.991835  ]


In [11]:
#Generate a 2-D array with 3 rows, each row containing 5 random numbers
from numpy import random
x = random.rand(3, 5)
print(x)

[[0.60708859 0.05581995 0.53457534 0.01918708 0.07627479]
 [0.68395551 0.96250134 0.51918301 0.91100058 0.80910795]
 [0.73745086 0.78506403 0.24519226 0.63464387 0.05103786]]


Generate Random Number From Array

*The choice() method allows you to generate a random value based on an array of values.

*The choice() method takes an array as a parameter and randomly returns one of the values.

In [13]:
#Return one of the values in an array
from numpy import random
x = random.choice([3, 5, 7, 9])
print(x)

7


In [14]:
#Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9)
from numpy import random
x = random.choice([3, 5, 7, 9], size=(3, 5))
print(x)

[[9 7 5 5 7]
 [7 7 9 5 3]
 [9 5 9 5 5]]
