Iterating Arrays

*Iterating means going through elements one by one.

*As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

*If we iterate on a 1-D array it will go through each element one by one.

In [1]:
#Iterate on the elements of the following 1-D array
import numpy as np
arr = np.array([1, 2, 3])
for x in arr:
  print(x)

1
2
3


Iterating 2-D Arrays

In [2]:
#Iterate on the elements of the following 2-D array
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [3]:
#Iterate on each scalar element of the 2-D array
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


Iterating 3-D Arrays

In [4]:
#Iterate on the elements of the following 3-D array
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [5]:
#Iterate down to the scalars
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


Iterating Arrays Using nditer()

In [6]:
#Iterate through the following 3-D array
import numpy as np
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [7]:
#Iterate through the array as a string
import numpy as np
arr = np.array([1, 2, 3])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


Iterating With Different Step Size

In [8]:
#Iterate through every scalar element of the 2D array skipping 1 element
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


Enumerated Iteration Using ndenumerate()

*Enumeration means mentioning sequence number of somethings one by one.

*Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

In [9]:
#Enumerate on following 1D arrays elements
import numpy as np
arr = np.array([1, 2, 3])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [10]:
#Enumerate on following 2D array's elements
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
