In [1]:
#Get the data type of an array object
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int64


In [2]:
#Get the data type of an array containing strings
import numpy as np
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


In [4]:
#Create an array with data type string
#For i, u, f, S and U we can define size as well.
import numpy as np
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [5]:
#Create an array with data type 4 bytes integer
import numpy as np
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [6]:
#Change data type from float to integer by using 'i' as parameter value
import numpy as np
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [7]:
#Change data type from float to integer by using int as parameter value
import numpy as np
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [8]:
#Change data type from integer to boolean
import numpy as np
arr = np.array([1, 0, 3])
newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool
